`timescale 1ns / 1ps
module testbench();
logic clk;
logic rst;
logic signed [15:0] sample_in;
logic valid_in;
logic ready;
logic valid_out;
logic signed [21:0] fft_real;
logic signed [21:0] fft_imag;

fft_64_streaming uut (
    .clk(clk),
    .rst(rst),

    .sample_in(sample_in),
    .valid_in(valid_in),

    .ready(ready),
    .valid_out(valid_out),

    .fft_real(fft_real),
    .fft_imag(fft_imag)
);


always #5 clk = ~clk;


integer i;
integer fin;
integer fout;
logic signed [15:0] input_mem [0:63];
logic signed [21:0] out_real [0:63];
logic signed [21:0] out_imag [0:63];



initial begin

    clk   = 1;
    rst   = 1;
    sample_in = 0;
valid_in  = 0;

for(i=0; i<64; i=i+1) begin
    input_mem[i] = 16'sd0;
    out_real[i]  = 22'sd0;
    out_imag[i]  = 22'sd0;
end

    #100;
    rst = 0;
    #20;

    //-------------------------------
    // Read input generated by MATLAB
    //-------------------------------
    fin = $fopen("C:/Users/utkar/OneDrive/Desktop/input_data.txt","r");

    if(fin == 0) begin
        $display("ERROR : Cannot open input_data.txt");
        $finish;
    end

    for(i=0;i<64;i=i+1)
$fscanf(fin,"%d",input_mem[i]);

    $fclose(fin);
    $display("");
$display("First 8 Input Samples:");

for(i=0;i<8;i=i+1)
    $display("input_mem[%0d] = %0d", i, input_mem[i]);

$display("");

    $display("--------------------------------------");
    $display("Input file loaded successfully.");
    $display("--------------------------------------");

@(posedge clk);
wait(ready == 1);

for(i=0;i<64;i=i+1) begin
    @(posedge clk);
    sample_in = input_mem[i];
    valid_in  = 1'b1;
end

@(posedge clk);
valid_in  = 1'b0;
sample_in = 16'sd0;


wait(valid_out == 1);
$display("FFT Output Streaming Started...");
fout = $fopen("C:/Users/utkar/OneDrive/Desktop/fft_output.txt","w");

if(fout == 0) begin
    $display("ERROR : Cannot create fft_output.txt");
    $finish;
end

for(i=0;i<64;i=i+1) begin
    @(posedge clk);
    out_real[i] = fft_real;
    out_imag[i] = fft_imag;
end

  for(i=0;i<64;i=i+1)

    $fdisplay(fout,"%0d %0d",
              out_real[i],
              out_imag[i]);

$fclose(fout);

    //-------------------------------
    // Print only significant bins
    //-------------------------------
    $display("");
    $display("======================================");
    $display("FFT OUTPUT SUMMARY");
    $display("======================================");

    for(i=0;i<64;i=i+1) begin

    if( (out_real[i] > 100)  ||
    (out_real[i] < -100) ||
    (out_imag[i] > 100)  ||
    (out_imag[i] < -100) )
        begin
            $display("Bin[%0d] = %0d + j%0d",
                     i,
                     out_real[i],
                     out_imag[i]);
        end

    end

    $display("======================================");
    $display("FFT completed successfully.");
    $display("Output written to fft_output.txt");
    $display("======================================");

    $finish;

end


endmodule

